// BU DOSYA URETILMISTIR - elle duzenleme.
// Ureten: scripts/vendor-sources.mjs
// Gomulu kaynak sayisi: 64
package com.berkstream

import com.lagradost.cloudstream3.plugins.BasePlugin

internal class VendoredSource(
    val id: String,
    val origin: String,
    val create: () -> BasePlugin,
)

internal val VENDORED_SOURCES: List<VendoredSource> = listOf(
    VendoredSource("4KFilmIzlesene", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.p4kfilmizlesene.nikyokki.`4KFilmIzlesenePlugin`() },
    VendoredSource("AnimeciX", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.animecix.keyiflerolsun.AnimeciXPlugin() },
    VendoredSource("AsyaAnimeleri", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.asyaanimeleri.keyiflerolsun.AsyaAnimeleriPlugin() },
    VendoredSource("AsyaWatch", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.asyawatch.nikyokki.AsyaWatchPlugin() },
    VendoredSource("BelgeselX", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.belgeselx.keyiflerolsun.BelgeselXPlugin() },
    VendoredSource("CanliTV", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.canlitv.keyiflerolsun.CanliTVPlugin() },
    VendoredSource("CizgiMax", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.cizgimax.keyiflerolsun.CizgiMaxPlugin() },
    VendoredSource("DailymotionProvider", "ReCloudStream Official Extensions") { com.berkstream.vendor.official.dailymotionprovider.recloudstream.DailymotionPlugin() },
    VendoredSource("Ddizi", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.ddizi.keyiflerolsun.DDiziPlugin() },
    VendoredSource("DiziBox", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.dizibox.keyiflerolsun.DiziBoxPlugin() },
    VendoredSource("DiziGom", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.dizigom.nikyokki.DiziGomPlugin() },
    VendoredSource("DiziKorea", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.dizikorea.keyiflerolsun.DiziKoreaPlugin() },
    VendoredSource("Dizilla", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.dizilla.keyiflerolsun.DizillaPlugin() },
    VendoredSource("DiziMag", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.dizimag.nikyokki.DiziMagPlugin() },
    VendoredSource("DiziMom", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.dizimom.keyiflerolsun.DiziMomPlugin() },
    VendoredSource("DiziPal", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.dizipal.keyiflerolsun.DiziPalPlugin() },
    VendoredSource("DiziPalOriginal", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.dizipaloriginal.keyiflerolsun.DiziPalOriginalPlugin() },
    VendoredSource("DiziYou", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.diziyou.keyiflerolsun.DiziYouPlugin() },
    VendoredSource("DMax", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.dmax.nikyokki.DMaxPlugin() },
    VendoredSource("FilmIzleIlk", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.filmizleilk.nikyokki.FilmIzleIlkPlugin() },
    VendoredSource("FilmKovasi", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.filmkovasi.nikyokki.FilmKovasiPlugin() },
    VendoredSource("FilmMakinesi", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.filmmakinesi.keyiflerolsun.FilmMakinesiPlugin() },
    VendoredSource("FilmModu", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.filmmodu.keyiflerolsun.FilmModuPlugin() },
    VendoredSource("FullHDFilm", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.fullhdfilm.keyiflerolsun.FullHDFilmPlugin() },
    VendoredSource("FullHDFilmİzlede", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.fullhdfilmizlede.nikyokki.FullHDFilmIzledePlugin() },
    VendoredSource("FullHDFilmizlesene", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.fullhdfilmizlesene.keyiflerolsun.FullHDFilmizlesenePlugin() },
    VendoredSource("HDFilmCehennemi", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.hdfilmcehennemi.keyiflerolsun.HDFilmCehennemiPlugin() },
    VendoredSource("HDFilmCehennemi2", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.hdfilmcehennemi2.nikyokki.HDFilmCehennemi2Plugin() },
    VendoredSource("HDFilmDelisi", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.hdfilmdelisi.patron.HDFilmDelisiPlugin() },
    VendoredSource("HDFilmIzle", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.hdfilmizle.nikyokki.HDFilmIzlePlugin() },
    VendoredSource("HDFilmSitesi", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.hdfilmsitesi.nikyokki.HDFilmSitesiPlugin() },
    VendoredSource("InatBox", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.inatbox.keyiflerolsun.InatBoxPlugin() },
    VendoredSource("InternetArchiveProvider", "ReCloudStream Official Extensions") { com.berkstream.vendor.official.internetarchiveprovider.recloudstream.InternetArchivePlugin() },
    VendoredSource("InvidiousProvider", "ReCloudStream Official Extensions") { com.berkstream.vendor.official.invidiousprovider.recloudstream.InvidiousPlugin() },
    VendoredSource("JetFilmizle", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.jetfilmizle.keyiflerolsun.JetFilmizlePlugin() },
    VendoredSource("KoreanTurk", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.koreanturk.keyiflerolsun.KoreanTurkPlugin() },
    VendoredSource("KultFilmler", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.kultfilmler.keyiflerolsun.KultFilmlerPlugin() },
    VendoredSource("powerDizi", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.powerdizi.keyiflerolsun.powerDiziPlugin() },
    VendoredSource("powerSinema", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.powersinema.keyiflerolsun.powerSinemaPlugin() },
    VendoredSource("RareFilmm", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.rarefilmm.keyiflerolsun.RareFilmmPlugin() },
    VendoredSource("RecTV", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.rectv.keyiflerolsun.RecTVPlugin() },
    VendoredSource("RoketDizi", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.roketdizi.nikyokki.RoketDiziPlugin() },
    VendoredSource("SelcukFlix", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.selcukflix.keyiflerolsun.SelcukFlixPlugin() },
    VendoredSource("SetFilmIzle", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.setfilmizle.keyiflerolsun.SetFilmIzlePlugin() },
    VendoredSource("SezonlukDizi", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.sezonlukdizi.keyiflerolsun.SezonlukDiziPlugin() },
    VendoredSource("SinemaCX", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.sinemacx.keyiflerolsun.SinemaCXPlugin() },
    VendoredSource("Sinewix", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.sinewix.keyiflerolsun.SinewixPlugin() },
    VendoredSource("SuperFilmGeldi", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.superfilmgeldi.keyiflerolsun.SuperFilmGeldiPlugin() },
    VendoredSource("TLC", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.tlc.nikyokki.TLCPlugin() },
    VendoredSource("TLCtr", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.tlctr.keyiflerolsun.TlctrPlugin() },
    VendoredSource("TRanimaci", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.tranimaci.keyiflerolsun.TRanimaciPlugin() },
    VendoredSource("TRasyalog", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.trasyalog.keyiflerolsun.TRasyalogPlugin() },
    VendoredSource("TurkAnime", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.turkanime.keyiflerolsun.TurkAnimePlugin() },
    VendoredSource("TvDiziler", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.tvdiziler.nikyokki.TvDizilerPlugin() },
    VendoredSource("TwitchProvider", "ReCloudStream Official Extensions") { com.berkstream.vendor.official.twitchprovider.recloudstream.TwitchPlugin() },
    VendoredSource("UgurFilm", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.ugurfilm.keyiflerolsun.UgurFilmPlugin() },
    VendoredSource("vavooSpor", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.vavoospor.keyiflerolsun.vavooSporPlugin() },
    VendoredSource("Watch2Movies", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.watch2movies.keyiflerolsun.Watch2MoviesPlugin() },
    VendoredSource("WebdramaTurkey2", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.webdramaturkey2.patron.WebdramaTurkey2Plugin() },
    VendoredSource("WebteIzle", "Feroxx Turkish Providers") { com.berkstream.vendor.feroxx.webteizle.keyiflerolsun.WebteIzlePlugin() },
    VendoredSource("WFilmİzle", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.wfilmizle.nikyokki.WFilmIzlePlugin() },
    VendoredSource("XPrime", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.xprime.nikyokki.XPrimePlugin() },
    VendoredSource("YabanciDizi", "Nikyokki Turkish Providers") { com.berkstream.vendor.nikyokki.yabancidizi.nikyokki.YabanciDiziPlugin() },
    VendoredSource("YoutubeProvider", "ReCloudStream Official Extensions") { com.berkstream.vendor.official.youtubeprovider.recloudstream.YoutubePlugin() },
)
